name = "OutlierDetectionTrees"
uuid = "6470b2ab-4fe8-498e-808d-6badd5c3da38"
authors = ["David Muhr <muhrdavid@gmail.com> and contributors"]
version = "0.1.0"

[deps]
OutlierDetectionInterface = "1722ece6-f894-4ffc-b6be-6ca1174e2011"

[compat]
julia = "1"
OutlierDetectionInterface = "0.1"

[extras]
OutlierDetectionTest = "66620973-d34b-445b-a614-4040704cad69"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "OutlierDetectionTest"]
